version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: 
  - Visual Studio 2019
  - Ubuntu2004

init:
  - ps: git config --global core.autocrlf false

nuget:
  disable_publish_on_pr: true

environment:
  NPM_TOKEN:
    secure: Gx5yyFrlELZY4DNW/uAuiXdhUADacNqi3LptQwldv8O61KpYyiDUniA8lBJ5jfne

install:
  - ps: docker-compose up -d --scale exchange-service=5

before_build:
  - ps: |
      $ErrorActionPreference = "Stop"
      $tagName = $env:APPVEYOR_REPO_TAG_NAME
      if ($tagName -match '^v\d+\.\d+') # tag name starts with 'vX.Y'
      {
        $version = $tagName.Substring(1)
        $env:SHOULD_PUBLISH_NUGET_PACKAGE = "true"
        Write-Host "Will publish nuget package for $tagName tag" -ForegroundColor "Green"
        if ($tagName -match '^v\d+\.\d+-release') # tag name starts with 'vX.Y-release' (e.g. use 'v4.2-release.1' tag for the first patch for release v4.2)
        {
          $version = $version.Substring(0, $version.IndexOf("-release"))
          $env:SHOULD_CREATE_RELEASE = "true"
          Write-Host "Will create release for $tagName tag" -ForegroundColor "Green"
        }
        $matchVersion = Select-String -Path ./version.json -Pattern "`"version`": `"$version`""
        if ($matchVersion -eq $null)
        {
          Write-Error "Version in tag ($version) does not match version in version.json"
        }
      }
  - ps: dotnet --info
  - ps: dotnet restore ./Cassandra.DistributedTaskQueue.sln --verbosity minimal
  - ps: dotnet tool restore
  - ps: cd cassandra-distributed-task-queue-ui && yarn install --frozen-lockfile

build_script:
  - ps: dotnet build --configuration Release ./Cassandra.DistributedTaskQueue.sln
  - ps: dotnet pack --no-build --configuration Release ./Cassandra.DistributedTaskQueue.sln
  - ps: cd cassandra-distributed-task-queue-ui && yarn build

test_script:
  - ps: dotnet jb cleanupcode Cassandra.DistributedTaskQueue.sln --profile=CatalogueCleanup --verbosity=WARN
  - ps: git diff --exit-code
  - ps: dotnet test --no-build --configuration Release ./Cassandra.DistributedTaskQueue.Tests/Cassandra.DistributedTaskQueue.Tests.csproj
  - ps: cd cassandra-distributed-task-queue-ui && yarn lint

after_test:
  - ps: |
      if ($env:SHOULD_PUBLISH_NUGET_PACKAGE -eq "true")
      {
        npm config set '//registry.npmjs.org/:_authToken' $env:NPM_TOKEN
        $fileNames = Get-ChildItem -Path "cassandra-distributed-task-queue-ui/dist" -Recurse -Include *.tgz
        foreach ($file in $fileNames)
        {
          Write-Host "Will publish npm package $($file.Name)" -ForegroundColor "Green"
          npm publish $file.FullName --quiet
        }
      }

artifacts:
  - path: './Cassandra.DistributedTaskQueue*/bin/Release/*.nupkg'
  - path: './cassandra-distributed-task-queue-ui/dist/*.tgz'

deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: 3Myenol+seNdEnkmH7tadxQLsmOE7VWQSp6vQii4vt2dX1S7XwjNV4T24HQTUsrr
    skip_symbols: true
    on:
      SHOULD_PUBLISH_NUGET_PACKAGE: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: y8dDOcAtq4U1MTDJFX8f23xsvyFU1u4bhwr9Lzbkf2revNWPPTifBkWghris9v8i
    draft: false
    prerelease: false
    on:
      SHOULD_CREATE_RELEASE: true
