version: "3"
services:
  cassandra:
    container_name: rtq-cassandra
    image: cassandra:3.11
    environment:
      - CASSANDRA_START_RPC=true
    ports:
      - 9042:9042
      - 9160:9160
  elasticsearch:
    container_name: rtq-elasticsearch
    image: elasticsearch:${ES_VERSION:-7.14.2}
    environment:
      - discovery.type=single-node
      - http.port=9205
      - http.publish_host=_local_
    ports:
      - 9205:9205
      - 9300:9300
  exchange-service:
    image: test-exchange-service
    build:
      context: .
      dockerfile: Cassandra.DistributedTaskQueue.TestExchangeService/Dockerfile
    environment:
      - CASSANDRA_ADDRESS=cassandra
      - ES_VERSION=${ES_VERSION:-7.14.2}
    ports:
      - "4403-4407:80"
    depends_on:
      - cassandra
  monitoring-service:
    image: test-monitoring-service
    build:
      context: .
      dockerfile: Cassandra.DistributedTaskQueue.Monitoring.TestService/Dockerfile
    environment:
      - ES_URL=http://elasticsearch:9205
      - ES_VERSION=${ES_VERSION:-7.14.2}
      - CASSANDRA_ADDRESS=cassandra
    ports:
      - "4413:80"
    depends_on:
      - cassandra
      - elasticsearch
