version: "3"
services:
  cassandra:
    container_name: rtq-cassandra
    image: registry.kontur.host/edi/edi-cassandra:3.11
    ports:
      - 9042:9042
      - 9160:9160
  elasticsearch:
    container_name: rtq-elasticsearch
    image: registry.kontur.host/edi/edi-elasticsearch:6.2
    ports:
      - 9205:9205
      - 9305:9305
