on: [push]
jobs:
  rtq-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            compose: docker-compose.linux.yaml
          - os: windows-2022
            compose: docker-compose.yaml
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Check docker version
        run: docker info
      - name: Build docker-compose environment
        run: docker-compose -f ${{ matrix.compose }} up -d --build
      - name: Check containers
        run: docker ps -a
      - name: Run tests
        run: dotnet test --configuration Release
